application:
  name: simple-example-node-3
  project: getting-started
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- name: my-mongodb
  type: mongodb
  version: 3.6
routers:
- name: hello
  routes:
  - application_name: simple-example-node-3
    paths:
    - /
